spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      database: 0
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}