services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: feedbook
      POSTGRES_PASSWORD: manager0
      POSTGRES_USER: manager
      TZ: "Asia/Seoul"
    ports:
      - 5432:5432
    volumes:
      - './db/schema.sql:/docker-entrypoint-initdb.d/init.sql'

  redis:
    image: 'redis:7.2.5'
    ports:
      - 6379:6379
    environment:
      TZ: "Asia/Seoul"